resources:
  - github.com/mNi-Cloud/api-gateway/config/default

images:
  - name: controller:latest
    newName: ghcr.io/mni-cloud/api-gateway
    newTag: "0.2"

patches:
  - target:
      kind: Deployment
      name: api-gateway-controller-manager
      namespace: api-gateway-system
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --cors-allow-origins=https://yakumo.mnicloud.jp,https://yakumo-api.mnicloud.jp,https://v2.mnicloud.jp,https://v2-api.mnicloud.jp
