resources:
  - https://github.com/mNi-Cloud/api-gateway//config/default?ref=v2.0.3

images:
  - name: controller
    newName: ghcr.io/mni-cloud/api-gateway
    newTag: "2.0.3"

patches:
  - target:
      kind: Deployment
      name: api-gateway-controller-manager
      namespace: api-gateway-system
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --cors-allow-origins=https://yakumo.mnicloud.jp,https://yakumo-api.mnicloud.jp,https://v2.mnicloud.jp,https://v2-api.mnicloud.jp
