apiVersion: v1
kind: ConfigMap
metadata:
  name: bs-ui-config
  namespace: bs-controller-system
data:
  VITE_API_BASE_URL: "http://api-gateway-gateway-service.api-gateway-system.svc.cluster.local"
  VITE_API_NAMESPACE: "default"
