helmCharts:
  - name: dependency-controller
    repo: https://charts.mnicloud.jp
    version: 0.1.12
    releaseName: dependency-controller
    namespace: dependency-controller

resources:
- namespace.yaml
