resources:
  - github.com/mNi-Cloud/vm-controller/config/default
  - github.com/mNi-Cloud/vm-ui/config/default
  - cdi-clone-rbac.yaml

images:
  - name: controller:latest
    newName: ghcr.io/mni-cloud/vm-controller
    newTag: "2.0"
  - name: ui:latest
    newName: ghcr.io/mni-cloud/vm-ui
    newTag: "0.1"

patches:
  - path: ui.yaml

