apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/mNi-Cloud/k8s-controller//config/default?ref=v1.0.10
images:
  - name: controller
    newName: ghcr.io/mni-cloud/k8s-controller
    newTag: "v1.0.10"
patches:
  - path: platform-config.yaml
