apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/mNi-Cloud/cert-ui//config/default?ref=v1.0.2

images:
  - name: ui
    newName: ghcr.io/mni-cloud/cert-ui
    newTag: "1.0.2"
