apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/mNi-Cloud/cert-controller//config/default?ref=v1.0.1

images:
  - name: controller
    newName: ghcr.io/mni-cloud/cert-controller
    newTag: "1.0.1"

patches:
  - target:
      kind: Namespace
      name: cert-controller-system
    patch: |-
      - op: add
        path: /metadata/labels/api-gateway.mnicloud.jp~1routes-enabled
        value: "true"
