resources:
  - https://github.com/mNi-Cloud/kodiak//config/default?ref=v1.0.0
  - https://github.com/mNi-Cloud/vpn-controller//config/default?ref=v1.0.4
  - https://github.com/mNi-Cloud/vpn-ui//config/default?ref=v1.0.0

images:
  - name: ui
    newName: ghcr.io/mni-cloud/vpn-ui
    newTag: "1.0.0"

patches:
  - path: ui.yaml
  - target:
      kind: Deployment
      name: kodiak-controller-manager
      namespace: kodiak-system
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/mni-cloud/kodiak:v1.0.0
  - target:
      kind: Deployment
      name: vpn-controller-controller-manager
      namespace: vpn-controller-system
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/mni-cloud/vpn-controller:v1.0.4
