resources:
  - https://github.com/mNi-Cloud/ctr-controller//config/default?ref=v2.0.2
  - https://github.com/mNi-Cloud/ctr-ui//config/default?ref=v0.1.3

images:
  - name: controller
    newName: ghcr.io/mni-cloud/ctr-controller
    newTag: "2.0.2"
  - name: ui
    newName: ghcr.io/mni-cloud/ctr-ui
    newTag: "0.1.3"

patches:
  - path: ui.yaml
