apiVersion: v1
kind: ConfigMap
metadata:
  name: ctr-ui-config
data:
  VITE_API_BASE_URL: "http://api-gateway-gateway-server-service.api-gateway-system.svc.cluster.local"
  VITE_API_NAMESPACE: "default"
