apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-api
  - capi-kamaji
  - cluster-api-addon-provider-helm
  - capmni
  - caa-provider-kubernetes
  - controller
  - ui
