resources:
  - https://github.com/mNi-Cloud/bs-controller//config/default?ref=v1.0.4
  - https://github.com/mNi-Cloud/bs-ui//config/default?ref=v0.1.4

images:
  - name: controller
    newName: ghcr.io/mni-cloud/bs-controller
    newTag: "1.0.4"
  - name: ui
    newName: ghcr.io/mni-cloud/bs-ui
    newTag: "0.1.4"

patches:
  - path: ui.yaml
