apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/1outres/juneau//install?ref=v1.0.0-rc.12
images:
  - name: ghcr.io/1outres/juneau/controller
    newTag: v1.0.0-rc.12
  - name: ghcr.io/1outres/juneau/daemon
    newTag: v1.0.0-rc.12
  - name: ghcr.io/1outres/juneau/bgp-speaker
    newTag: v1.0.0-rc.12
  - name: ghcr.io/1outres/juneau/webhookcertjob
    newTag: v1.0.0-rc.12
