apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/mNi-Cloud/ctr-controller//config/default?ref=v1.0.10
images:
  - name: controller
    newName: ghcr.io/mni-cloud/ctr-controller
    newTag: "1.0.10"
